ccflags-y := -Idrivers/scsi

rts5139-y := rts51x_transport.o rts51x_scsi.o rts51x_fop.o rts51x.o rts51x_chip.o rts51x_card.o xd.o sd.o ms.o sd_cprm.o ms_mg.o

obj-$(CONFIG_USB_CARDREADER_RTS5139) += rts5139.o
