obj-y += init.o setup.o irq.o time.o pci.o pm.o
obj-$(CONFIG_EARLY_PRINTK) += early_printk.o
#obj-$(CONFIG_SERIAL_8250) += uart.o
obj-$(CONFIG_SMP) += smp.o
obj-$(CONFIG_USE_OF)  += dts/
obj-$(CONFIG_SWIOTLB) += swiotlb.o
obj-$(CONFIG_PCI_MSI) += pci_msi.o
#
#HPET Support
#
obj-$(CONFIG_LS2K_HPET) += hpet.o
